package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import dao.CredentialCSVDAO;
import model.CredentialRecord;
import service.EmployeeService;
import service.PasswordService;
import service.ResourcePathService;

public class Registration extends JFrame {

    private static final Color BRAND_TEAL = new Color(0, 102, 102);
    private static final Color BRAND_DARK = new Color(0, 51, 51);
    private static final Color TEXT_DARK = new Color(33, 37, 41);
    private static final Color TEXT_MUTED = new Color(108, 117, 125);
    private static final Color BORDER_GRAY = new Color(206, 212, 218);
    private static final Color BG_FIELD = new Color(255, 255, 255);

    private final EmployeeService employeeService;
    private final CredentialCSVDAO credentialDAO;

    private JTextField employeeNumberField;
    private JTextField employeeNameField;
    private JTextField emailField;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JPasswordField confirmPasswordField;
    private JCheckBox showPasswordCheck;
    private JLabel statusLabel;
    private String lastAutoGeneratedEmail = "";

    public Registration() {
        this.employeeService = new EmployeeService();
        this.credentialDAO = new CredentialCSVDAO();
        initComponents();
    }

    private void initComponents() {
        setTitle("REGISTER");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setLayout(new BorderLayout());

        add(buildFormPanel(), BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }

    private JPanel buildFormPanel() {
        JPanel formPanel = new JPanel(new GridBagLayout());
        formPanel.setBackground(Color.WHITE);
        formPanel.setPreferredSize(new Dimension(700, 680));
        formPanel.setBorder(new EmptyBorder(34, 120, 34, 120));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 5, 0);
        gbc.gridx = 0;
        gbc.weightx = 1.0;

        JLabel titleLabel = new JLabel("REGISTER");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 34));
        titleLabel.setForeground(BRAND_DARK);
        titleLabel.setHorizontalAlignment(JLabel.CENTER);
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 26, 0);
        formPanel.add(titleLabel, gbc);

        gbc.insets = new Insets(8, 0, 3, 0);
        gbc.gridy = 1;
        formPanel.add(createFieldLabel("Employee #"), gbc);

        employeeNumberField = createTextField();
        employeeNumberField.addActionListener(evt -> populateEmployeeName());
        employeeNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                populateEmployeeName();
            }
        });
        gbc.gridy = 2;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(employeeNumberField, gbc);

        gbc.gridy = 3;
        gbc.insets = new Insets(8, 0, 3, 0);
        formPanel.add(createFieldLabel("Employee Name (auto-filled)"), gbc);

        employeeNameField = createTextField();
        employeeNameField.setEditable(false);
        employeeNameField.setBackground(new Color(248, 249, 250));
        gbc.gridy = 4;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(employeeNameField, gbc);

        // Keep employee name synced with employee number without requiring Enter/focus loss.
        employeeNumberField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                populateEmployeeName();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                populateEmployeeName();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                populateEmployeeName();
            }
        });

        gbc.gridy = 5;
        gbc.insets = new Insets(8, 0, 3, 0);
        formPanel.add(createFieldLabel("Email Address"), gbc);

        emailField = createTextField();
        gbc.gridy = 6;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(emailField, gbc);

        gbc.gridy = 7;
        gbc.insets = new Insets(8, 0, 3, 0);
        formPanel.add(createFieldLabel("User Name"), gbc);

        usernameField = createTextField();
        gbc.gridy = 8;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(usernameField, gbc);

        gbc.gridy = 9;
        gbc.insets = new Insets(8, 0, 3, 0);
        formPanel.add(createFieldLabel("Password"), gbc);

        passwordField = createPasswordField();
        gbc.gridy = 10;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(passwordField, gbc);

        gbc.gridy = 11;
        gbc.insets = new Insets(8, 0, 3, 0);
        formPanel.add(createFieldLabel("Confirm Password"), gbc);

        confirmPasswordField = createPasswordField();
        gbc.gridy = 12;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(confirmPasswordField, gbc);

        showPasswordCheck = new JCheckBox("Show passwords");
        showPasswordCheck.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        showPasswordCheck.setForeground(TEXT_MUTED);
        showPasswordCheck.setBackground(Color.WHITE);
        showPasswordCheck.addActionListener(evt -> togglePasswordVisibility());
        gbc.gridy = 13;
        gbc.insets = new Insets(2, 0, 10, 0);
        formPanel.add(showPasswordCheck, gbc);

        statusLabel = new JLabel(" ");
        statusLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        statusLabel.setForeground(TEXT_MUTED);
        gbc.gridy = 14;
        gbc.insets = new Insets(0, 0, 10, 0);
        formPanel.add(statusLabel, gbc);

        JButton submitButton = new JButton("Submit Registration");
        submitButton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        submitButton.setBackground(BRAND_TEAL);
        submitButton.setForeground(Color.WHITE);
        submitButton.setFocusPainted(false);
        submitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        submitButton.setBorder(BorderFactory.createEmptyBorder(12, 20, 12, 20));
        submitButton.addActionListener(evt -> handleRegistration());
        gbc.gridy = 15;
        gbc.insets = new Insets(4, 0, 16, 0);
        formPanel.add(submitButton, gbc);
        getRootPane().setDefaultButton(submitButton);

        JLabel backToLogin = new JLabel("Back to Login");
        backToLogin.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        backToLogin.setForeground(BRAND_TEAL);
        backToLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new UserLogin().setVisible(true);
                dispose();
            }
        });

        gbc.gridy = 16;
        gbc.insets = new Insets(0, 0, 0, 0);
        formPanel.add(backToLogin, gbc);

        return formPanel;
    }

    private JLabel createFieldLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(new Font("Segoe UI", Font.BOLD, 14));
        label.setForeground(TEXT_DARK);
        return label;
    }

    private JTextField createTextField() {
        JTextField field = new JTextField();
        field.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        field.setBackground(BG_FIELD);
        field.setForeground(TEXT_DARK);
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(BORDER_GRAY, 1),
                BorderFactory.createEmptyBorder(10, 12, 10, 12)));
        field.setPreferredSize(new Dimension(0, 42));
        return field;
    }

    private JPasswordField createPasswordField() {
        JPasswordField field = new JPasswordField();
        field.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        field.setBackground(BG_FIELD);
        field.setForeground(TEXT_DARK);
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(BORDER_GRAY, 1),
                BorderFactory.createEmptyBorder(10, 12, 10, 12)));
        field.setPreferredSize(new Dimension(0, 42));
        return field;
    }

    private void togglePasswordVisibility() {
        char echo = showPasswordCheck.isSelected() ? (char) 0 : '\u2022';
        passwordField.setEchoChar(echo);
        confirmPasswordField.setEchoChar(echo);
    }

    private void populateEmployeeName() {
        String empNumber = employeeNumberField.getText().trim();
        if (empNumber.isEmpty()) {
            employeeNameField.setText("");
            maybeApplyAutoEmail("");
            return;
        }

        String csvFile = ResourcePathService.resourceFile("EmployeeDetails_AdminView.csv");
        try {
            EmployeeLookup lookup = findEmployeeLookup(csvFile, empNumber);
            if (lookup != null) {
                employeeNameField.setText(lookup.fullName);
                maybeApplyAutoEmail(lookup.generatedEmail);
                setStatus("Employee found.", new Color(25, 135, 84));
            } else {
                employeeNameField.setText("");
                maybeApplyAutoEmail("");
                setStatus("Employee number not found.", new Color(220, 53, 69));
            }
        } catch (Exception e) {
            employeeNameField.setText("");
            maybeApplyAutoEmail("");
            setStatus("Unable to validate employee right now.", new Color(220, 53, 69));
        }
    }

    private EmployeeLookup findEmployeeLookup(String csvFile, String employeeNumber) throws Exception {
        List<String[]> rows = employeeService.getEmployees(csvFile);
        for (int i = 1; i < rows.size(); i++) {
            String[] row = rows.get(i);
            if (row.length < 3) {
                continue;
            }

            String empNo = row[0] == null ? "" : row[0].trim();
            if (!empNo.equals(employeeNumber.trim())) {
                continue;
            }

            String lastName = row[1] == null ? "" : row[1].trim();
            String firstName = row[2] == null ? "" : row[2].trim();
            String fullName = (firstName + " " + lastName).trim();

            String generatedEmail = buildGeneratedEmail(firstName, lastName, empNo);
            return new EmployeeLookup(fullName, generatedEmail);
        }

        return null;
    }

    private String buildGeneratedEmail(String firstName, String lastName, String employeeNumber) {
        String first = sanitizeAlphaNum(firstName).toLowerCase();
        String last = sanitizeAlphaNum(lastName).toLowerCase();
        String emp = sanitizeAlphaNum(employeeNumber).toLowerCase();

        if (first.isEmpty()) {
            first = "employee";
        }
        if (last.isEmpty()) {
            last = "user";
        }

        return first + "." + last + "." + emp + "@motorph.com";
    }

    private String sanitizeAlphaNum(String value) {
        if (value == null) {
            return "";
        }
        return value.replaceAll("[^A-Za-z0-9]", "");
    }

    private void maybeApplyAutoEmail(String generatedEmail) {
        String current = emailField.getText() == null ? "" : emailField.getText().trim();

        // Only auto-fill when empty or when the current value is the previous auto-generated one.
        if (current.isEmpty() || current.equalsIgnoreCase(lastAutoGeneratedEmail)) {
            emailField.setText(generatedEmail);
            lastAutoGeneratedEmail = generatedEmail;
        }
    }

    private static class EmployeeLookup {
        private final String fullName;
        private final String generatedEmail;

        private EmployeeLookup(String fullName, String generatedEmail) {
            this.fullName = fullName;
            this.generatedEmail = generatedEmail;
        }
    }

    private void handleRegistration() {
        String employeeNumber = employeeNumberField.getText().trim();
        String employeeNameInput = employeeNameField.getText().trim();
        String email = emailField.getText().trim();
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());

        if (employeeNumber.isEmpty() || employeeNameInput.isEmpty() || email.isEmpty()
                || username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            setStatus("Please fill in all fields.", new Color(220, 53, 69));
            return;
        }

        if (!password.equals(confirmPassword)) {
            setStatus("Password and Confirm Password do not match.", new Color(220, 53, 69));
            return;
        }

        if (!isValidEmail(email)) {
            setStatus("Please enter a valid email address.", new Color(220, 53, 69));
            return;
        }

        String employeeCsv = ResourcePathService.resourceFile("EmployeeDetails_AdminView.csv");
        String credentialCsv = ResourcePathService.resourceFile("MotorPHcredentialLogin.csv");

        try {
            String expectedFullName = employeeService.findFullNameByEmployeeNumber(employeeCsv, employeeNumber);
            if (expectedFullName == null) {
                setStatus("Employee number was not found.", new Color(220, 53, 69));
                return;
            }

            if (!expectedFullName.equalsIgnoreCase(employeeNameInput)) {
                setStatus("Employee name does not match the employee number.", new Color(220, 53, 69));
                return;
            }

            List<CredentialRecord> credentials = credentialDAO.loadAllCredentials(credentialCsv);

            for (CredentialRecord record : credentials) {
                if (record.getUserName() != null
                        && record.getUserName().equalsIgnoreCase(username)
                        && (record.getEmployeeNumber() == null
                        || !record.getEmployeeNumber().trim().equals(employeeNumber))) {
                    setStatus("Username is already in use.", new Color(220, 53, 69));
                    return;
                }
            }

            boolean updated = false;
            String hashedPassword = PasswordService.hash(password);
            for (int i = 0; i < credentials.size(); i++) {
                CredentialRecord record = credentials.get(i);
                if (record.getEmployeeNumber() != null
                        && record.getEmployeeNumber().trim().equals(employeeNumber)) {
                    credentials.set(i, new CredentialRecord(
                            employeeNumber,
                            email,
                            username,
                            hashedPassword,
                            "EMPLOYEE",
                            "ACTIVE"));
                    updated = true;
                    break;
                }
            }

            if (!updated) {
                credentials.add(new CredentialRecord(
                        employeeNumber,
                        email,
                        username,
                    hashedPassword,
                        "EMPLOYEE",
                        "ACTIVE"));
            }

            credentialDAO.saveAllCredentials(credentialCsv, credentials);
            JOptionPane.showMessageDialog(this,
                    updated ? "Account details updated successfully." : "Registration successful.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            new UserLogin().setVisible(true);
            dispose();
        } catch (Exception e) {
            setStatus("Unable to complete registration: " + e.getMessage(), new Color(220, 53, 69));
        }
    }

    private boolean isValidEmail(String email) {
        return email != null
                && email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    private void setStatus(String message, Color color) {
        statusLabel.setText(message);
        statusLabel.setForeground(color);
    }
}
